# Generated by Django 6.0.8 on 2026-09-10 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('junior-high', 'Junior High School'), ('senior-high', 'Senior High School'), ('undergraduate', 'Undergraduate')], max_length=30)),
                ('entry_year', models.PositiveIntegerField()),
                ('graduation_year', models.PositiveIntegerField()),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('utbk_score', models.PositiveIntegerField(blank=True, null=True)),
                ('logo_path', models.CharField(blank=True, max_length=255)),
                ('experience_anchor', models.SlugField(max_length=30, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'entry_year'],
            },
        ),
    ]
