# Generated by Django 5.0 on 2026-09-21 08:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('projects', models.ManyToManyField(blank=True, related_name='skills', to='main.project')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
